### ISSUE TITLE
 WARNING: A newer version of conda exists.

### ISSUE THREAD

**Issue by IljaK91** [JuliaPy/Conda.jl#100]
I get the following message when I run `using Conda; Conda.update();` : 

```
==> WARNING: A newer version of conda exists. <==
  current version: 4.4.2
  latest version: 4.4.7

Please update conda by running

    $ conda update -n base conda
```

What can I do about it? If I run conda update -n root conda, it updates the existing Anaconda 3 installation.

**Comment by stevengj** [comment]
`Conda.update("conda", "base")`, I think?

**Comment by IljaK91** [comment]
That worked! Thank you 👍

**Comment by stevengj** [comment]
Maybe we should do this automatically in `Conda.update()`?
