### ISSUE TITLE
Install a package using pip in Conda.jl

### ISSUE THREAD

**Issue by finmod** [JuliaPy/Conda.jl#101]
How do I install a package, which is not in the continuum repos, using pip:

In python, it would like to install pycma as follows:

pip install -e cma or 
pip install git+https://github.com/CMA-ES/pycma.git@master

Conda.list() tells me that pip is already installed.

What is the syntax for Conda.add() in Julia?

> using Conda
> Conda. add("")

**Comment by stevengj** [comment]
Duplicate of #50.
