### ISSUE TITLE
Conda.add("numpy") hangs on a Mac OS with python2

### ISSUE THREAD

**Issue by favba** [JuliaPy/Conda.jl#107]
```
julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc350 (2018-05-28 20:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

I was unable to build PyCall. The problem reduced to:
```
julia> Conda.add("numpy")
Fetching package metadata .................
Solving package specifications: .
```

where it just hang there for hours, when I eventually interrupted the execution. This happened for several tries for several days.

I was able to build PyCall by changing to python 3
```
julia> using Conda

julia> rm(Conda.ROOTENV, recursive=true)

julia> ENV["CONDA_JL_VERSION"]=3
3

julia> Pkg.build("Conda")
INFO: Building Conda
```

**Comment by stevengj** [comment]
Are you behind a corporate firewall?

**Comment by favba** [comment]
No. I tried this at my University and at home. It didn't work on both places.

**Comment by favba** [comment]
I just tried setting it to python 2 again and it worked.
I just remembered that I've upgraded julia (v0.6.2 -> v0.6.3) a few days ago. Maybe that, somehow, messed things up?

It seems what worked wasn't changing to python 3, but deleting the root folder `rm(Conda.ROOTENV, recursive=true)` and building again.

**Comment by stevengj** [comment]
Unfortunately, it's going to be hard to debug this if we can't figure out a way reproduce it.

(Maybe your `conda` was simply out of date and you needed to run `Conda.update()`?)

**Comment by favba** [comment]
I haven't been able to reproduce the issue, therefore I am closing this.
