### ISSUE TITLE
PyError - IOError (2, No such file or directory)

### ISSUE THREAD

**Issue by lucasfreitas1988** [JuliaPy/Conda.jl#109]
Hello! I need Help!

My code - df = DataFrame(load("Lebron.xlsx", "Sheet1")) - results in

PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <type 'exceptions.IOError'>
IOError(2, 'No such file or directory')
File "C:\Users\ACER.julia\v0.6\Conda\deps\usr\lib\site-packages\xlrd_init_.py", line 116, in open_workbook with open(filename, "rb") as f:

This is a Conda error or an problem with ExcelFiles Package?

Thank you

**Comment by stevengj** [comment]
Looks like a problem with ExcelFiles.

**Comment by stevengj** [comment]
If it is even a problem at all.  `No such file or directory` makes it sound like `Lebron.xlsx` does not exist in the current directory.

For example, does `isfile("Lebron.xlsx")` return `true`?
