### ISSUE TITLE
conda installs outside of JULIA_DEPOT_PATH

### ISSUE THREAD

**Issue by ksmcreynolds** [JuliaPy/Conda.jl#128]
I updated Conda.jl to v1.1.0 and realized that `conda` was being installed in my home directory instead of the depot directory. On our cluster, the home directory has very poor performance so I need to install it elsewhere. However, it appears from the build script that the build path is hardcoded to the home directory. Is there an environment variable that can change the install directory (I am under the impression that `CONDA_JL_HOME` only works for existing installations)? 

On a more general note, is there a reason the home directory was chosen over the depot directory? It was unexpected to me that a Julia package would install something outside of the depot directory.

Having said all that, given how long `conda` installations take on our cluster (due to poor NFS performance), I really appreciate that Conda.jl will not reinstall `conda` for every new version. 👍

**Comment by stevengj** [comment]
Your case didn't occur to me; you're right, this is a good reason to use `first(DEPOT_PATH)` instead of `~/.julia`.  (@tkf suggested this in #126, but it wasn't clear that it made a difference).
