### ISSUE TITLE
error when adding ORCA.jl

### ISSUE THREAD

**Issue by ezgikurt** [JuliaPy/Conda.jl#144]
Hi, 
I run into an error in Conda.add( ) when trying to build ORCA.jl. (see [here](https://github.com/sglyon/ORCA.jl/issues/8) for the issue in ORCA package)

The error message I get is the following: 
```
 DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
│ Use 'conda create' to convert the directory to a conda environment.
│   target directory: C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps

│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
│  [4] run at .\process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::String) at C:\Users\ezgik\.julia\packages\Conda\CpuvI\src\Conda.jl:113
│  [6] add(::String, ::String) at C:\Users\ezgik\.julia\packages\Conda\CpuvI\src\Conda.jl:183
│  [7] top-level scope at none:0
│  [8] include at .\boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps\build.jl:5
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\
Operations.jl:1075
```

I've tried doing what it says - I've used the Anaconda prompt to convert the directory to a conda environment with the following command. 
```
conda create --prefix C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps
```
This seemed worked and ORCA built fine but then had issues in precompiling.  For some people this step seems to solve their problems but for me it did not. My colleague also tried the same on a fresh install of v1.1 today and ran into the same problem. 

```
ERROR: InitError: IOError: could not spawn `'C:\Users\ezgik\.julia\packages\ORCA\ZfBvW\deps\orca_app\orca' server --port
=7982 --graph-only`: no such file or directory (ENOENT)
```
I see a similar issue here #13 by @stevengj from 2015, which I think was fixed so I cannot figure out what's going on. Any help appreciated!

**Comment by stevengj** [comment]
The initial error is because you are passing a non-empty non-Anaconda directory as the environment, I think — Anaconda doesn't seem to like that, but seems happy if you pass it an empty directory (which it will initialize for you).

The other error seems like a problem with ORCA.jl looking in the wrong path.  Anyway, I think further discussion of this should occur in the ORCA.jl issue.
