### ISSUE TITLE
On Windows shortcuts for existing Anaconda install are overwritten

### ISSUE THREAD

**Issue by krcools** [JuliaPy/Conda.jl#147]
If you have Anaconda installed on Windows (unrelated to Julia), the installation of Miniconda causes the start menu shortcuts to be overwritten.

In particular opening a conda prompt by clicking on the relevant start menu entry lands you in the `.julia/conda/3` environment.

Is there a way to stop this from happening?

**Comment by stevengj** [comment]
It seems like this an issue with the miniconda installer (see e.g. https://github.com/ContinuumIO/anaconda-issues/issues/136#issuecomment-319948447) … it's not clear if there is a way to disable it.

**Comment by RoyiAvital** [comment]
@stevengj, Could the process use do the decompressing of files manually instead of running the installer?
That way it will also not be registered in Application in Windows:

![image](https://user-images.githubusercontent.com/7347975/113293163-15cc6f80-92fe-11eb-94b2-ff742602d3bb.png)

**Comment by RoyiAvital** [comment]
Maybe using the `/NoRegistry` flag?
See https://github.com/conda/conda/issues/10502.

**Comment by RoyiAvital** [comment]
@stevengj , It seems that adding the `/NoRegistry=1` to https://github.com/JuliaPy/Conda.jl/blob/master/src/Conda.jl#L208 will prevent the installation to be registered by Windows.

Could you add it?

**Comment by RoyiAvital** [comment]
It seem `conda` made a progress on their side as well in https://github.com/conda/constructor/issues/452.

**Comment by stevengj** [comment]
Should be closed by daf770366773d975e97204dc7c3c86521cfcfb5a

**Comment by RoyiAvital** [comment]
@stevengj , Following the updated documentation in https://conda.github.io/constructor/cli-options I created https://github.com/JuliaPy/Conda.jl/pull/254.
