### ISSUE TITLE
When building Conda : syntax: incomplete: premature end of input

### ISSUE THREAD

**Issue by Maestox** [JuliaPy/Conda.jl#149]
Hi!
I'm a beginner in Julia, so I hope that my message isn't useless. I'm on ArchLinux.

- The README file isn't up-to-date anymore : `add("Conda")` isn't right anymore (that doesn't work on my Julia's version) : `add PyCall` is used instead, as `build Conda` must be used instead of `build("Conda")`
- I've juste tried to install Conda, I get this error : 

`Building Conda → `~/.julia/packages/Conda/CpuvI/deps/build.log`
┌ Error: Error building `Conda`: 
│ ERROR: LoadError: syntax: incomplete: premature end of input
│ Stacktrace:
│  [1] top-level scope at none:2
│ in expression starting at /home/louis/.julia/packages/Compat/HiX6E/src/Compat.jl:3
│ ERROR: LoadError: Failed to precompile Compat [34da2185-b29b-5c13-b0c7-acf172513d20] to /home/louis/.julia/compiled/v1.1/Compat/GSFWK.ji.
│ Stacktrace:
│  [1] include(::String) at ./client.jl:403
│  [2] top-level scope at none:0
│ in expression starting at /home/louis/.julia/packages/Conda/CpuvI/deps/build.jl:1
└ @ Pkg.Operations /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075`

[I've tried to build Conda, because the adding of PyCall didn't work]

**Comment by stevengj** [comment]
`Pkg.add("Conda")` at the `julia>` prompt still works, but you have to `import Pkg`'.  Or you can `add Conda` at the `pkg>` prompt.

You definitely don't use `add PyCall` — it is *not necessary* to add PyCall to get Conda.   Running `add Conda` automatically runs `build Conda` after it installs.

Regarding the error you are seeing, evidently this is a problem with Compat.jl and should be reported there.
