### ISSUE TITLE
Possibly go straight to Python 3.8

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/Conda.jl#153]
I note outdated: "The last alpha release, Python 3.8.0a4, is planned for 2019-04-29."

You may want to wait for a non-alpha, or think about support sooner. I see there are at least some interesting additions:

https://www.python.org/dev/peps/pep-0572/ 

https://www.python.org/dev/peps/pep-0570/ [Was this added in 3.8? See: https://bugs.python.org/issue36540 ]

https://bugs.python.org/issue36742
https://bugs.python.org/issue36276
https://bugs.python.org/issue35372
https://bugs.python.org/issue36312

**Comment by stevengj** [comment]
We use whatever is the default in Anaconda.
