### ISSUE TITLE
function add does not accept keyword arguments

### ISSUE THREAD

**Issue by tk3369** [JuliaPy/Conda.jl#155]
Unable to add package with channel specified... 🤔 

```
julia> Conda.add("pykafka", Conda.ROOTENV; channel = "conda-forge")
ERROR: function add does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:330
 [2] top-level scope at none:0
```

**Comment by FelixJones42** [comment]
I'm running into the same problem with
julia> Conda.add("openmm",:ROOTENV; channel="omnia")
ERROR: function add does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:330
 [2] top-level scope at none:0

**Comment by sjkelly** [comment]
This runs fine for me on master. It looks like https://github.com/JuliaPy/Conda.jl/pull/139 did not make it into the 1.2.0 tag. @rofinn is it possible to do a new release?

**Comment by rofinn** [comment]
Huh, I am a JuliaPy maintainer :/ I guess so. Might be good to get @ararslan or @stevengj to make the release since that was my PR?

**Comment by sjkelly** [comment]
@tk3369 you can try running `pyimport_conda("pykafka", "pykafka", "conda-forge")` from PyCall and it should add the dependency.
