### ISSUE TITLE
Scipy.interpolate

### ISSUE THREAD

**Issue by henry2004y** [JuliaPy/Conda.jl#159]
Hi,

I was trying to install Scipy on Mac OSX 10.12.6 throught Conda using Julia 1.1. It was installed successfully, but I couldn't import Scipy.interpolate, receiving info that this specific subpackage was not installed.

**Comment by stevengj** [comment]
```jl
using Conda, PyCall
Conda.add("scipy")
pyimport("scipy.interpolate")
```
works for me.

**Comment by henry2004y** [comment]
I just tried to uninstall and install scipy again. Now it works, so I don't know what was happening then. It's just so weird.
