### ISSUE TITLE
Can I use pre-exist Anaconda?

### ISSUE THREAD

**Issue by timsu92** [JuliaPy/Conda.jl#180]
I'm sorry if this question sounds odd 😥

I noticed [the doc](https://juliaobserver.com/packages/Conda)  says we can use pre-exist Conda environments. However, it also says `/path/to/`**miniconda**`/envs/conda_jl`
Therefore, I'm wondering if I can use Anaconda.

Thanks for answering!

**Comment by stevengj** [comment]
Did you read: https://github.com/JuliaPy/Conda.jl#using-a-pre-existing-conda-installation

**Comment by timsu92** [comment]
OK, thank you for your answering!
