### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mfherbst** [JuliaPy/Conda.jl#191]
I have a workflow depending on pip support (changes of #171). Would it be possible to make a new release and get that version into the repo?

**Comment by ali-ramadhan** [comment]
Also hoping to see a new tagged release. Been having to tell collaborators to `] add Conda#master` to get around https://github.com/JuliaPy/Conda.jl/pull/188.

**Comment by stevengj** [comment]
Will be closed by https://github.com/JuliaRegistries/General/pull/24040
