### ISSUE TITLE
unable to build IJulia due to "Conda is not properly configured"

### ISSUE THREAD

**Issue by fpmenninger** [JuliaPy/Conda.jl#194]
in Julia 1.5.3, 1.5.2 and 1.0.5 similar results...
Not sure what else to try.
Code is below.
Thanks for help.
```
(@v1.5) pkg> add Conda
   Updating registry at `E:\ProgramFiles\Julia\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Updating `E:\ProgramFiles\Julia\.julia\environments\v1.5\Project.toml`
  [8f4d0f93] + Conda v1.5.0
No Changes to `E:\ProgramFiles\Julia\.julia\environments\v1.5\Manifest.toml`

(@v1.5) pkg> build Conda

(@v1.5) pkg> build IJulia
   Building IJulia → `E:\ProgramFiles\Julia\.julia\packages\IJulia\a1SNk\deps\build.log`
┌ Error: Error building `IJulia`:
│ ERROR: LoadError: Conda is not properly configured.  Run Pkg.build("Conda") before importing the Conda module.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] top-level scope at E:\ProgramFiles\Julia\.julia\packages\Conda\x5ml4\src\Conda.jl:25
│  [3] include(::Function, ::Module, ::String) at .\Base.jl:380
│  [4] include(::Module, ::String) at .\Base.jl:368
│  [5] top-level scope at none:2
│  [6] eval at .\boot.jl:331 [inlined]
│  [7] eval(::Expr) at .\client.jl:467
│  [8] top-level scope at .\none:3
│ in expression starting at E:\ProgramFiles\Julia\.julia\packages\Conda\x5ml4\src\Conda.jl:21
│ ERROR: LoadError: Failed to precompile Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] to E:\ProgramFiles\Julia\.julia\compiled\v1.5\Conda\WZE3U_n7Ivt.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1305
│  [3] _require(::Base.PkgId) at .\loading.jl:1030
│  [4] require(::Base.PkgId) at .\loading.jl:928
│  [5] require(::Module, ::Symbol) at .\loading.jl:923
│  [6] include(::String) at .\client.jl:457
│  [7] top-level scope at none:5
│ in expression starting at E:\ProgramFiles\Julia\.julia\packages\IJulia\a1SNk\deps\build.jl:1
└ @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949       
```

**Comment by stevengj** [comment]
Try quitting Julia and restarting after `build Conda`.   Then what does `using Conda` do?

**Comment by fpmenninger** [comment]
gives about the same error...

julia> using Conda
[ Info: Precompiling Conda [8f4d0f93-b110-5947-807f-2305c1781a2d]
ERROR: LoadError: Conda is not properly configured.  Run Pkg.build("Conda") before importing the Conda module.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at E:\ProgramFiles\Julia\.julia\packages\Conda\x5ml4\src\Conda.jl:25
 [3] include(::Function, ::Module, ::String) at .\Base.jl:380
 [4] include(::Module, ::String) at .\Base.jl:368
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:331 [inlined]
 [7] eval(::Expr) at .\client.jl:467
 [8] top-level scope at .\none:3
in expression starting at E:\ProgramFiles\Julia\.julia\packages\Conda\x5ml4\src\Conda.jl:21
ERROR: Failed to precompile Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] to E:\ProgramFiles\Julia\.julia\compiled\v1.5\Conda\WZE3U_3YUoD.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1305
 [3] _require(::Base.PkgId) at .\loading.jl:1030
 [4] require(::Base.PkgId) at .\loading.jl:928
 [5] require(::Module, ::Symbol) at .\loading.jl:923

**Comment by stevengj** [comment]
Is there a `deps.jl` file in `E:\ProgramFiles\Julia.julia\packages\Conda\x5ml4\deps`?

**Comment by fpmenninger** [comment]
No, there is no deps.jl file in the deps folder.
(And thank you for the help.)

**Comment by stevengj** [comment]
That's weird, it's written by these lines of the build: https://github.com/JuliaPy/Conda.jl/blob/dc1c1c77afe796f816a7fae29cacf87cacb56986/deps/build.jl#L50-L54

What is the log from `build Conda`?

**Comment by fpmenninger** [comment]
noticing that the only thing in the deps folder is the build.log

and the log file reads:
ERROR: could not open file E:\ProgramFiles\Julia\.julia\packages\Conda\x5ml4\deps\build.jl
Stacktrace:
 [1] include at .\boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1044
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] include(::String) at .\client.jl:392
 [5] top-level scope at none:0

Wondering if there's something going on with having both Julia 1.0.5, which removes
  Updating `E:\ProgramFiles\Julia\.julia\environments\v1.0\Manifest.toml`
  [4c555306] - ArrayLayouts v0.3.8
  [082447d4] - ChainRules v0.6.5
  [d360d2e6] - ChainRulesCore v0.8.1
  [7869d1d1] ↓ IRTools v0.4.1 ⇒ v0.3.3
  [46d2c3a1] - MuladdMacro v0.2.2
  [e88e6eb3] ↓ Zygote v0.4.22 ⇒ v0.4.8
whenever a package update is done, but then adds those packages back with "(v1.0) pkg> add Conda

**Comment by stevengj** [comment]
Does `E:\ProgramFiles\Julia.julia\packages\Conda\x5ml4\deps\build.jl` exist?  Has it somehow been set so that you don't have read permission?

**Comment by fpmenninger** [comment]
pkg> rm Conda
then deleted the Conda folder
pkg> add Conda
pkg> build Conda
and success.
So, didn't need to reinstall Julia, but did need to delete and reinstall the Conda package.
Thank you greatly!
