### ISSUE TITLE
Switch to Miniforge?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPy/Conda.jl#196]
See also: #195 

---

The terms of service for `repo.anaconda.com` (https://www.anaconda.com/terms-of-service) say the following:
> These Terms of Service (“Agreement”) relate to your use of the compilation of products and tools made available by Anaconda through https://repo.anaconda.com/ and through our installers and applications (the “Repository”) and serve to make it possible for Anaconda to continue to provide the Repository.
> 
> ...
> 
> So that we can be sure the Repository works as a resource for our community of developers, we are not granting you permission to use the Repository for commercial activities (as defined below) or in a way that could negatively impact other users, such as downloading or mirroring the entire Repository.

If I understand correctly, this means that you cannot use `repo.anaconda.com` for commercial usage.

Does Conda.jl use `repo.anaconda.com`?

**Comment by stevengj** [comment]
It uses whatever the default is for `conda`

**Comment by stevengj** [comment]
Apparently the [terms were changed in spring 2020](https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community).

**Comment by isuruf** [comment]
Yes, it does. Have a look at https://github.com/conda-forge/miniforge if you want to avoid the new terms of service.

**Comment by DilumAluthge** [comment]
> Yes, it does. Have a look at https://github.com/conda-forge/miniforge if you want to avoid the new terms of service.

I think it would be good for Conda.jl to switch over to using Miniforge.

Is Miniforge intended to be a drop-in replacement for Miniconda? If so, hopefully it won't be too difficult to make the switch.

**Comment by isuruf** [comment]
> Is Miniforge intended to be a drop-in replacement for Miniconda?

Yes. It also has more platforms like `linux-aarch64`, `osx-arm64`.

> If so, hopefully it won't be too difficult to make the switch.

Switching will make `conda-forge` the default channel and will change some things. For eg: the default blas package is OpenBLAS instead of MKL (you can switch to MKL though).

**Comment by stevengj** [comment]
Yes, I agree that Miniforge seems like the way to go at the moment.

**Comment by isuruf** [comment]
See https://github.com/JuliaPy/Conda.jl/pull/198

**Comment by bilderbuchi** [comment]
Does using Miniforge really avoid the new terms, though? While you are not using repo.anaconda.com, isn't `conda` still being used in Miniforge, and do you not thus end up using "our installers and applications" mentioned in the TOS?

**Comment by isuruf** [comment]
> isn't conda still being used in Miniforge,

conda is an open source project. What's not free from Anaconda, Inc is their binary packages from `repo.anaconda.com`.

> "our installers and applications"

Miniforge is a community effort by conda-forge (part of NumFOCUS) and Anaconda, inc has no control. They graciously provide free hosting on `anaconda.org` which is not under the TOS.

**Comment by bilderbuchi** [comment]
Ah, that's great, then! :-)

**Comment by stevengj** [comment]
Closed by #207.
