### ISSUE TITLE
installation failled with accent in user name

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaPy/Conda.jl#199]
I am trying to help two students who failed to install Conda.jl. A manual miniconda installation to the directory `c:\users\<username>\.julia\conda\3\` also failed. We see the following error in the miniconda installation log:

```
Traceback (most recent call last):
   File "concurrent\futures\process.py", line 368, in
_queue_management_worker
   File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
```

Both students have a French accent in their username which seems to be an issue for conda (at least [anaconda](https://docs.anaconda.com/anaconda/user-guide/faq/)):

> We recommend installing Anaconda or Miniconda into a directory that contains only 7-bit ASCII characters and no spaces, such as C:\anaconda. Do not install into paths that contain spaces such as C:\Program Files or that include Unicode characters outside the 7-bit ASCII character set. This helps ensure correct operation and no errors when using any open-source tools in either Python 3 or Python 2 conda environments.

Could `Conda.jl` detect this issue and propose a work-around to the users?
I cannot replicate the issue locally, but after reading [build.jl](https://github.com/JuliaPy/Conda.jl/blob/e5444efa5d830c6e85f37e61775d6f19f91f2f8c/deps/build.jl) it seems that setting `ENV["CONDA_JL_HOME"]`  might be sufficient. 

See also https://github.com/conda/conda/issues/10239

**Comment by stevengj** [comment]
See also https://github.com/conda/conda/issues/8662 … and also https://github.com/ContinuumIO/anaconda-issues/issues/716 for spaces in the path.

Yes, it seems feasible to print out a more friendly error message for paths that Anaconda doesn't like, just by checking `isascii(path) && ' ' ∉ path`.
