### ISSUE TITLE
Unable to update matplotlib through Conda

### ISSUE THREAD

**Issue by vishalhedgevantage** [JuliaPy/Conda.jl#206]
My current Julia env uses Conda dependencies within Julia. However I have run into a problem with PyPlot which cant work with matplotlib 3.3.2 version. It asks for upgrading matplotlib to 3.4.0. I have tried Conda.update() but latest version of matplotlib is never pulled.

**Comment by stevengj** [comment]
(PyPlot doesn't require matplotlib 3.3 as far as I recall?)

I just tried `Conda.update()` and it pulls matplotlib 3.4 for me:
```jl
julia> Conda.version("matplotlib")
v"3.4.2"
```
Maybe you pinned it at a particular version?
