### ISSUE TITLE
miniconda support for M1 macs

### ISSUE THREAD

**Issue by ctkelley** [JuliaPy/Conda.jl#208]
Just installed 1.7 on M1 mac. Started from scratch with no .julia directory.

Tried to fire up a notebook and got this
```
julia> notebook(;dir=pwd())
install Jupyter via Conda, y/n? [y]: y
[ Info: Downloading miniconda installer ...
ERROR: Unsupported miniconda platform: MacOSX-arm64
```

**Comment by giordano** [comment]
Note: I [already answered on discourse](https://discourse.julialang.org/t/ijulia-in-1-7-fails-on-mac-m1/72370/2)

**Comment by stevengj** [comment]
The next version will default to miniforge (#207).
