### ISSUE TITLE
how to call command line from Conda.jl

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaPy/Conda.jl#212]
After installing `Playwright` with 

```
Conda.pip("install", "playwright")
```

I am supposed to call

```
playwright install
```

to install `chromium` `firefox` `webkit` support. Is their any way to call this from Conda.jl julia env? 

`conda_jl` is env in my `minicoda3/envs`

**Comment by stevengj** [comment]
You should be able to do
```jl
playwright  = joinpath(Conda.BINDIR, "playwright")
run(`$playwright install`)
```

**Comment by AbhimanyuAryan** [comment]
Thankyou @stevengj
