### ISSUE TITLE
Failing to install miniconda on Windows

### ISSUE THREAD

**Issue by jebej** [JuliaPy/Conda.jl#230]
Not sure how recent of a problem this is, but while reinstalling conda, after wiping it from my `.julia` directory, I got the following error:
```
[ Info: Downloading miniconda installer ...
[ Info: Installing miniconda ...
ERROR: LoadError: failed process: Process(`'C:\Users\Jeremy\.julia\conda\3\installer.exe' /S --no-shortcuts /NoRegistry=1 /AddToPath=0 /RegisterPython=0 '/D=C:\Users\Jeremy\.julia\conda\3'`, ProcessExited(2)) [2]
Stacktrace:
  [1] pipeline_error
    @ .\process.jl:538 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base .\process.jl:453
  [3] run
    @ .\process.jl:451 [inlined]
  [4] _install_conda(env::String, force::Bool)
    @ Conda C:\Users\Jeremy\.julia\packages\Conda\x2UxR\src\Conda.jl:209
```

I ran the installer manually with the same settings and it complained that `C:\Users\Jeremy\.julia\conda\3` was not empty (which is true since the installer is there). It might be necessary to change the location of the installer exe file.

**Comment by JackDunnNZ** [comment]
I have the same problem on Windows and can confirm that changing the location of the installer fixes it (e.g. from `.julia\conda\3\installer.exe` to `.julia\conda\installer.exe`)

**Comment by stevengj** [comment]
See #231 for a potential fix.
