### ISSUE TITLE
New test failure on PackageEvaluator

### ISSUE THREAD

**Issue by tkelman** [JuliaPy/Conda.jl#36]
Surprised me a bit - https://gist.github.com/6da18a78a1fbb8b3380ca4221e95a102

`ERROR: LoadError: test failed: isempty(channels) || channels == ["defaults"]`

**Comment by Luthaf** [comment]
I can not reproduce it locally. I'll have a look at tomorrow results to see if something changed.

**Comment by tkelman** [comment]
Still happening it seems? http://pkg.julialang.org/detail/Conda.html

**Comment by Luthaf** [comment]
I still can not reproduce this. How are the tests run exactly ? Are the different julia versions tested in the same VM, or in a fresh environment ?

**Comment by tkelman** [comment]
The exact setup is here - https://github.com/JuliaCI/PackageEvaluator.jl/tree/master/scripts

All packages starting with A-L are run inside the same VM at the moment. So it might be one of the A, B, or C packages messing things up for you?

**Comment by isuruf** [comment]
https://github.com/chemfiles/Chemfiles.jl seems to be the culprit

**Comment by tkelman** [comment]
good catch. that should probably be cleaning up after itself

**Comment by Luthaf** [comment]
Good catch @isuruf!

Is there any way to register code to be executed when running `Pkg.rm("Foo")`? This would be the cleaner way to remove any artifacts.

In the mean time, I will add logic in the Conda.jl tests to save and load existing channels.

**Comment by tkelman** [comment]
No. Why do you need added channels to persist longer than the Pkg.build that needs to use them?

**Comment by Luthaf** [comment]
Because if the channel is missing but the package still installed, some of the calls to Conda functions will fails (I believe `update`, `version`, and maybe others)

**Comment by isuruf** [comment]
In `runtests.jl`, there is also one more bug. It removes `curl` and then reinstall it again. This is not a good solution because packages depending on curl like `cmake, libnetcdf` will be removed and then will not installed when `curl` is reinstalled.

**Comment by Luthaf** [comment]
Do I need to tag a new release, or do PackageEvaluator use the latest master?

**Comment by tkelman** [comment]
it tests tags, not master.
