### ISSUE TITLE
Problems with one environment

### ISSUE THREAD

**Issue by isuruf** [JuliaPy/Conda.jl#46]
Having one environment has several issues.
- Channel priority will be changed by each package using Conda.jl and it will downgrade or upgrade some packages when same package is in different channels like `defaults`, `conda-forge`.
- Features make it impossible to install some packages together. For example, a package that links against vs2015_runtime cannot be installed in a Python 2.7 environment because it uses an old vs2008_runtime. (I had to install Python 3.5 just to install a C package. This might cause problems with other Julia packages.)
- Conda.rm can screw up other Julia packages.

Therefore, having separate environments for each package in BinDeps is probably the best way forward.

**Comment by Luthaf** [comment]
Using separate environments could effectively be nice, but what happen in the following cases:

- I am `using` two packages with different BinDeps dependencies, and thus different environments?
- I am using the REPL, and trying to install Conda packages on the fly?

The other issue to be resolved here is how do we automatically switch between environments as needed?

For a related issue, see also #19.

**Comment by Luthaf** [comment]
Also, I think the proper way to solve this is to have some kind of julia virtualenv/per-project dependencies. Requiring all packages to be global will not scale with the number of packages growing.

**Comment by isuruf** [comment]
> I am using two packages with different BinDeps dependencies, and thus different environments?
Yes, but I do realize that for python dependencies that PyCall needs, this would have to install it into PyCall's environment. At least for C dependencies, different environments would work.

**Comment by isuruf** [comment]
You don't need to switch between environments. You can treat them as separate environments.

**Comment by Luthaf** [comment]
> You don't need to switch between environments. You can treat them as separate environments.

I though you need to `activate` an environment before using it. If you don't, this is easier to implement!

I do not have time to implement this feature, do you think you could give it a try? I'll be happy to review and merge a pull request.

**Comment by stevengj** [comment]
Note that PyCall needs to be re-built if you change the Python version from 2 to 3, so it's not clear how multiple environments can coexist in a usable way for it.

**Comment by stevengj** [comment]
Note that PyCall needs to be re-built if you change the Python version from 2 to 3, so it's not clear how multiple environments can coexist in a usable way for it.

**Comment by isuruf** [comment]
Yes, I know. For Python, it doesn't make sense. My use case is for non Python dependencies.

**Comment by stevengj** [comment]
Oh, I see; that makes sense.

**Comment by stevengj** [comment]
Closed by #47.
