### ISSUE TITLE
Links to packages that are using Conda.jl?

### ISSUE THREAD

**Issue by oxinabox** [JuliaPy/Conda.jl#49]
Hi,
I am trying to get my head around exactly how to use Conda.jl
with BinDeps.

It would really help to have an example of it being used in a actual package.

It would thus be nice to have a link to one (or two) in the readme.

**Comment by Luthaf** [comment]
Yes, that would be nice. 

If you are using a native dependency, you can have a look [here](https://github.com/chemfiles/Chemfiles.jl/blob/4de865e9062ed78a2544ee88a2939e9899ca0ec8/deps/build.jl#L8-L15) or [here](https://github.com/wkearn/RasterIO.jl/blob/78125ba71bfd664e61d5fa7d682c971d3a1bb7f5/deps/build.jl).

If you need a Python dependency, PyCall provides a `pyimport_conda` function that try to import a module, and install it using Conda if it is not available.
