### ISSUE TITLE
A Documented/Preferred way of installing PyPi dependencies

### ISSUE THREAD

**Issue by oxinabox** [JuliaPy/Conda.jl#50]
So Conda (unlike anaconda) can not install dependencies using PyPi, as a source.
(AFAICT, after an afternoon of looking).

I believe the docs currently suggest creating a Conda package and uploading it to binstar.org.

Which is actually rather annoying to do, since now you are maintaining a distribution channel for your dependencies -- you don't get updated when the providers do them,  you have to make sure it works on all platforms etc.
It is unfun.

So currently my work around for installing things, is to automate how I would do it manually.
Which is: tell Conda to install pip, then have pip install other things. (
Inspired by https://github.com/JuliaPy/Conda.jl/issues/30#issuecomment-183307329)

https://github.com/oxinabox/SwiftObjectStores.jl/blob/fee6a7bdd6d4b9a1a6865b95f4629d919a28947b/deps/build.jl

Is this the best way? If so, it should be documented.
If not, a better way should be documented.

There are a lot of python libraries in PyPi, that are not in any Conda channel, that I trust to keep them up-to-date, and with it all working for all OS's.

As far as I can tell, `PyCall.py_import_conda`, does not help here, since it only downloads things from Conda channels.

**Comment by Luthaf** [comment]
> As far as I can tell, PyCall.py_import_conda, does not help here, since it only downloads things from Conda channels.

Yes, `PyCall.py_import_conda` only uses Conda.

> Is this the best way? If so, it should be documented.
> If not, a better way should be documented.

There is no absolute best way, just do whatever suites your need. I see at least five ways of having a Python dependency for Julia code:

- Use Conda by creating a conda package and using a custom channel;
- Use Conda to install pip and use pip to install your dependency;
- Use PyCall with whichever Python distribution is installed, and then use [git-pip.y](https://pip.pypa.io/en/stable/installing/) to install pip. This could be the base of a `Pip.jl` package actually;
- Include the Python dependency in your repo as a git submodule/vendor direcory;
- Use the system package manager to get the dependencies (`python-*` packages are available in most Linux distributions), and rely on the existing BinDep providers;

The first four can be equally convenient, depending on the dependency, and your requirements. If you are going for Linux only code, the last one if the one that require the less work.

All these could be documented, but I would rather have them documented in a Python specific package that in Conda.jl. `conda` is not a Python package manager, it is a generic package manager written in Python (like yum), and used by the major scientific python distributions.

**Comment by isuruf** [comment]
To add to the first point, you can use, [conda-forge](http://conda-forge.github.io/) to build packages across platforms using CI services.

**Comment by stevengj** [comment]
Is there a downside to using Conda's pip?  That has the advantage of not depending on (or affecting) a system Python.   Could using pip with Conda generate conflicts with ordinary Conda packages?

**Comment by isuruf** [comment]
Yes, there could be conflicts. If the pip package has a dependency that is given in Conda and the pip package asks for a specific version of the dependency then pip might install a newer version of the package in Conda.

**Comment by Luthaf** [comment]
I just found this [old gist](https://gist.github.com/Luthaf/368a23981c8ec095c3eb) of mine, using only PyCall to install pip as needed and then use it to download the dependencies.

This could be used by PyCall to provide an `install` function, switching on the backend: if Conda.jl is used, check if the package is available trough conda and install it. In all the other cases, check if it is available with pip and install it.

**Comment by Luthaf** [comment]
If you are working with a custom conda package (I assume you are the one publishing it, perhaps in a custom channel), I believe the best option would be to create and upload conda packages for your dependencies too. There are tools around to create a conda package from a `setup.py` file.

**Comment by arnavs** [comment]
> Is there a downside to using Conda's pip for things that don't have Conda packages? 

As above, how exactly does one do this? @stevengj, I saw that you closed #101, but as far as I can tell this hasn't been addressed.

**Comment by oxinabox** [comment]
I actually think making a **Pip.jl** package that acts a lot like Conda.jl (or HomeBrew.jl kinda).
would be pretty good at this point.
Because I gather a lot of the improvements that Conda has over Pip have now been added to pip (like binaries in wheels? idk I am not a python person.)

PyPi has way move than Conda,
and for most use cases Conda.jl is used exclusively for installing python stuff.
(Even though it can do more.)

Big downside is that it would be impossible to have PyCall using both with in the same process.
So the whole ecosystem would need to move or support both.

**Comment by arnavs** [comment]
I think that's a good idea. Alternately you could just wrap a short script to do what we did after installing `Conda.jl` and `Conda.add("pip")` 

```
from pip._internal import main 
main(['install', '--pre', 'dfogn'])
```

**Comment by tkf** [comment]
IPython 7.3 will have `%pip` magic command https://github.com/ipython/ipython/pull/11524 which can be used via IPython.jl https://github.com/tkf/IPython.jl; sorry, kind of an ad :)
