### ISSUE TITLE
Using an existing miniconda3

### ISSUE THREAD

**Issue by dmbates** [JuliaPy/Conda.jl#53]
I prefer to use python3 and have installed it and several packages using miniconda3. The instructions for using and existing conda with `Conda.jl` indicate that I should create a new conda environment, say `conda_jl`, with python and perhaps other packages, then pass the location as `ENV["CONDA_JL_HOME"]`

Is it necessary to create this new environment or can I just use the default conda environment for `Conda.jl`?  My primary use of the conda packages will be through Julia PyCall.

**Comment by isuruf** [comment]
Yes. you can. You'll have to first build `Conda.jl` and then build `PyCall.jl` (You'll have to make sure `PyCall` picks up the correct python library. See PyCall README for how to do that). Instructions to use a new conda environment was to not mess up your default conda environment, but if you really want to, you can.

Btw, `PyCall` can use an existing miniconda3 environment even without `Conda.jl`.

**Comment by stevengj** [comment]
Python 3 is supported these days.
