### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by isuruf** [JuliaPy/Conda.jl#55]
When do you plan to get a new release (with #47) in METADATA.jl?

**Comment by isuruf** [comment]
@stevengj, @Luthaf, ping

**Comment by Luthaf** [comment]
Done [here](https://github.com/JuliaLang/METADATA.jl/pull/6851). 

@isuruf if you are interested to help maintaining Conda, we could add you as a collaborator. @stevengj what do you think?

**Comment by isuruf** [comment]
Thanks for doing the release.
I'd be happy to help with maintaining Conda.jl

**Comment by Luthaf** [comment]
Ping @stevengj, could you give @isuruf write right for Conda.jl ?

**Comment by stevengj** [comment]
Sure, done.

**Comment by stevengj** [comment]
I also changed @Luthaf to admin status, since I noticed you only had committer rights.

**Comment by Luthaf** [comment]
Thanks!

**Comment by isuruf** [comment]
Thanks
