### ISSUE TITLE
Automatically detect a conda installation

### ISSUE THREAD

**Issue by isuruf** [JuliaPy/Conda.jl#59]
We could automatically detect a conda installation at built time, create an environment named `conda_jl` and use it.
What do you think?

cc @musm

**Comment by stevengj** [comment]
I'm a little bit worried about being bitten by broken/out-of-date conda installations.   I've seen horrible things on the machines of my students.

**Comment by isuruf** [comment]
Thanks for the info, is it because of broken conda environments (where there are lots of packages interfering)?
This shouldn't be a problem because we are creating a new environment. But if it's a broken conda installation, then yes we will be better off not doing this.

**Comment by stevengj** [comment]
For example, what if someone just has a really ancient Conda installed?

**Comment by Luthaf** [comment]
I am not completely sold on that. What are the benefits? The current code can do a lot of assumption about the state of the conda installation that we will loose doing this.

As I see it, this package is more an interface to conda packages, that append to use the `conda` python script, but that an implementation detail. The script could be removed or changed for something else without breaking for the users.

**Comment by stevengj** [comment]
It seems like we are unlikely to do this.
