### ISSUE TITLE
miniconda-latest installer

### ISSUE THREAD

**Issue by arklian** [JuliaPy/Conda.jl#64]
The miniconda installer url looks for "https://repo.continuum.io/miniconda/Miniconda-latest-" but https://repo.continuum.io/miniconda seems to only offer Miniconda2-latest- and Miniconda3-latest.

When I try to use Conda.Add, I get
ERROR: automatic download failed (error: 2148270086): http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe

Should this be fixed, or am I doing something wrong.

**Comment by lanzafame** [comment]
There is only a "https://repo.continuum.io/miniconda/Miniconda-latest-" for Linux. But as the [download page](https://repo.continuum.io/miniconda/) says "Note: the Miniconda-latest-* installers are Miniconda2-* installers."

**Comment by Luthaf** [comment]
Looks like Miniconda changed the installers names. I'll fix this.

**Comment by Luthaf** [comment]
The fix is published in https://github.com/JuliaLang/METADATA.jl/pull/7825.
