### ISSUE TITLE
broken install on 32-bit windows?

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/Conda.jl#65]
The PyCall and PyPlot tests seem to be breaking on 32-bit windows.  It says "Downloading the miniconda installer," but it seems like nothing else is installed?   (See JuliaPy/PyPlot.jl#279)

**Comment by arklian** [comment]
Quite sure it's the same problem as #64

**Comment by Luthaf** [comment]
Can you try again now that #64 has been fixed and published?

**Comment by stevengj** [comment]
Okay, I resubmitted the PyCall AppVeyor build: https://ci.appveyor.com/project/StevenGJohnson/pycall-jl-nu3aa

**Comment by stevengj** [comment]
Yay, looks like it is working now!
