### ISSUE TITLE
Share Conda installation between Julia versions

### ISSUE THREAD

**Issue by dpsanders** [JuliaPy/Conda.jl#73]
It would be nice not to have to use a different Conda installation for each different version of Julia (0.5, 0.6 and 0.7 currently).

**Comment by isuruf** [comment]
You can first install Conda.jl for 0.5 and then set `CONDA_JL_HOME` to `$HOME/.julia/v0.5/Conda/deps/usr` and build Conda.jl for others. See https://github.com/JuliaPy/Conda.jl#using-an-already-existing-conda-installation

**Comment by dpsanders** [comment]
Ah, good idea, thanks.
