### ISSUE TITLE
MINICONDA_VERSION not defined

### ISSUE THREAD

**Issue by eunjongkim** [JuliaPy/Conda.jl#85]
Hi, I'm having an issue with building Conda. The console returns error messages like this:
```
====================================================[ ERROR: Conda ]====================================================

LoadError: UndefVarError: MINICONDA_VERSION not defined
while loading C:\Users\ekim7\.julia\v0.6\Conda\deps\build.jl, in expression starting on line 13

========================================================================================================================
```
anyone having idea on this issue?

**Comment by isuruf** [comment]
Can you remove `C:\Users\ekim7\.julia\v0.6\Conda\deps\deps.jl` and try again?

**Comment by eunjongkim** [comment]
@isuruf  Thanks. It works!

**Comment by nil-8** [comment]
I had the same issue, and removing deps.jl worked for me too.

**Comment by stevengj** [comment]
We should fix `build.jl` so that manually removing `deps.jl` is not required.

**Comment by stevengj** [comment]
In the meantime, the platform-independent workaround is:
```jl
rm(Pkg.dir("Conda","deps","deps.jl"))
Pkg.build("Conda)
```
