### ISSUE TITLE
When moving miniconda folder, Conda.jl always refuses to be re-built.

### ISSUE THREAD

**Issue by denchat** [JuliaPy/Conda.jl#90]
Since I moved miniconda to a different folder, I can not build Conda.jl apon external miniconda anymore.  
Wiping .julia, .conda, reinstall julia, miniconda all do not help.  

This is the error

    julia> Pkg.build("Conda")
    INFO: Building Conda
    ====================================================[ ERROR: Conda ]====================================================

    LoadError: Miniconda version changed, since last build.
    However, a root enviroment already exists at C:/Users/Sand/AppData/Local/Miniconda/envs/conda_jl.
    Setting Miniconda version is not supported for existing root enviroments.
    To leave Miniconda version as, it is unset the CONDA_JL_VERSION enviroment variable and rebuild.
    To change Miniconda version, you must delete the root enviroment and rebuild.
    WARNING: deleting the root enviroment will delete all the packages in it.
    This will break many Julia packages that have used Conda to install their dependancies.
    These will require rebuilding.

    while loading C:\Users\Sand\.julia\v0.6\Conda\deps\build.jl, in expression starting on line 19

by "you must delete the root enviroment and rebuild", what am I supposed to do?

**Comment by dawidmon** [comment]
When you first build miniconda environment you've probably did this by running Pkg.add("Conda") command. If you analyze the contents of the "build.jl" file you will notice that in such cases the default miniconda version is 2:

(...)
if !isdefined(:MINICONDA_VERSION)
        const MINICONDA_VERSION = "2"
(...)

During the first run of "build.jl" a "deps.jl" file is created/updated.
Within "deps.jl" file you will find a line giving your miniconda version from initial build:

const MINICONDA_VERSION = "2".

Whatever you do to your miniconda installation after, "deps.jl" seems not to get an update.
If later you update your miniconda installation to version 3, manually changing

const MINICONDA_VERSION = "2"

to

const MINICONDA_VERSION = "3"

should do the trick.

You should be able to run Pkg.build("Conda") further without such notice.

**Comment by isuruf** [comment]
Remove `C:\Users\Sand\.julia\v0.6\Conda\deps\usr` folder and `C:\Users\Sand\.julia\v0.6\Conda\deps\deps.jl`

**Comment by denchat** [comment]
Thanks. More over, unset CONDA_JL_VERSION is also necessary.
