### ISSUE TITLE
404 error with Conda.add("jupyter")

### ISSUE THREAD

**Issue by crbinz** [JuliaPy/Conda.jl#92]
I initially ran into this when [trying to install IJulia](https://github.com/JuliaLang/IJulia.jl/issues/590):

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Conda

julia> Conda.add("jupyter")
Fetching package metadata .....

CondaHTTPError: HTTP 404 None
for url <None>

The remote server could not find the channel you requested.

You will need to adjust your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.



ERROR: failed process: Process(setenv(`/Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda install -y jupyter`,String["CLICOLOR=1", "LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD", "COMMAND_MODE=unix2003", "PATH=/Applications/Julia-0.6.app/Contents/Resources/julia/bin:/Users/cbinz/anaconda/bin:/usr/local/bin:/user/local/bin://anaconda/bin:/usr/local/heroku/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin", "PWD=/Users/cbinz/Code/ETR.jl", "XPC_FLAGS=0x0", "DISPLAY=/private/tmp/com.apple.launchd.iuZq4t3HPl/org.macosforge.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=iTerm.app", "SHELL=/bin/bash", "ITERM_PREV_PS1=\\[\e]133;D;\$?\a\e]133;A\a\\]\\h:\\W \\u\\\$ \\[\e]133;B\a\\]", "__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0", "COLORFGBG=12;8", "TMPDIR=/var/folders/sm/j5dkyxzs38l0gp30b8wv78340000gn/T/", "TK_LIBRARY=/System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts", "CONDARC=/Users/cbinz/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "FONTCONFIG_PATH=/Applications/Julia-0.6.app/Contents/Resources/julia/etc/fonts", "LANG=en_US.UTF-8", "ITERM_PROFILE=Default", "PS1=\\h:\\W \\u\\\$ ", "SHLVL=1", "LOGNAME=cbinz", "CONDA_PREFIX=/Users/cbinz/.julia/v0.6/Conda/deps/usr", "OLDPWD=/Users/cbinz/Code/ExtentParticleFilter.jl", "TERM_SESSION_ID=w0t3p0:4FB884BE-DF43-4181-A58B-51B462B9E791", "SSH_AGENT_PID=44458", "SSH_AUTH_SOCK=/var/folders/sm/j5dkyxzs38l0gp30b8wv78340000gn/T//ssh-ttZYY3712Xcq/agent.44457", "_=/usr/local/bin/julia", "CONDA_DEFAULT_ENV=/Users/cbinz/.julia/v0.6/Conda/deps/usr", "Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.YL7NvyDesR/Render", "USER=cbinz", "SM7=cbinz@132.250.138.171", "SECURITYSESSIONID=186a5", "ITERM_ORIG_PS1=\\h:\\W \\u\\\$ ", "ITERM_SESSION_ID=w0t3p0:4FB884BE-DF43-4181-A58B-51B462B9E791", "TERM=xterm-256color", "HOME=/Users/cbinz", "TERM_PROGRAM_VERSION=3.1.beta.10", "OPENBLAS_MAIN_FREE=1", "COLORTERM=truecolor"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] add(::String) at /Users/cbinz/.julia/v0.6/Conda/src/Conda.jl:209
```

This is just from my home network, so there should be no firewall issues.

**Comment by isuruf** [comment]
Can you run `/Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda list` and `/Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda info` from a terminal and comment the output here?

**Comment by crbinz** [comment]
Sure:

```
MacBook-Air:~ cbinz$ /Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda list
# packages in environment at /Users/cbinz/.julia/v0.6/Conda/deps/usr:
#
cffi                      1.9.1                    py27_0
conda                     4.2.13                   py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
cryptography              1.7.1                    py27_0
enum34                    1.1.6                    py27_0
idna                      2.2                      py27_0
ipaddress                 1.0.18                   py27_0
mkl                       2017.0.1                      0
numpy                     1.12.1                   py27_0
openssl                   1.0.2k                        0
pip                       9.0.1                    py27_1
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.17                     py27_0
pyopenssl                 16.2.0                   py27_0
python                    2.7.13                        0
readline                  6.2                           2
requests                  2.12.4                   py27_0
ruamel_yaml               0.11.14                  py27_1
setuptools                27.2.0                   py27_0
sgp4                      1.4                      py27_2    conda-forge
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
yaml                      0.1.6                         0
zlib                      1.2.8                         3

MacBook-Air:~ cbinz$ /Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/cbinz/.julia/v0.6/Conda/deps/usr  (writable)
    default environment : /Users/cbinz/.julia/v0.6/Conda/deps/usr
       envs directories : /Users/cbinz/.julia/v0.6/Conda/deps/usr/envs
          package cache : /Users/cbinz/.julia/v0.6/Conda/deps/usr/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/cbinz/.condarc
           offline mode : False
```

**Comment by isuruf** [comment]
Can you do ` /Users/cbinz/.julia/v0.6/Conda/deps/usr/bin/conda update conda` and then try building IJulia again?

**Comment by crbinz** [comment]
This fixed it - it installed successfully. Thanks.

**Comment by WenFuLee** [comment]
I have the same issue, but "conda update conda" seems not to work. Could you help me? Below is the info you may need.
-------------------------------------------------------------------------------------------
Wen-Fus-MacBook-Pro:bin wen-fulee$ conda list
-bash: conda: command not found
Wen-Fus-MacBook-Pro:bin wen-fulee$ ./conda list
# packages in environment at /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0            py27hb466136_0  
asn1crypto                0.23.0           py27h862e517_0  
backports                 1.0              py27hb4f9756_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
bleach                    2.1.2                    py27_0  
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2018.1.18                py27_0  
cffi                      1.11.2           py27h21b8a49_0  
chardet                   3.0.4            py27h2842e91_1  
conda                     4.4.10                   py27_0  
conda-env                 2.6.0                h36134e3_0  
configparser              3.5.0            py27hc7edf1b_0  
cryptography              2.1.4            py27hdbc5e8f_0  
dbus                      1.12.2               haa0f8f7_0  
decorator                 4.2.1                    py27_0  
entrypoints               0.2.3            py27hd680fb1_2  
enum34                    1.1.6            py27hf475452_1  
expat                     2.2.5                hb8e80ba_0  
functools32               3.2.3.2          py27h8ceab06_1  
futures                   3.2.0            py27h1b80678_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.53.6               h33f6a65_2  
html5lib                  1.0.1            py27h5233db4_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py27hedea723_1  
ipaddress                 1.0.18           py27h5b9a5b9_0  
ipykernel                 4.8.0                    py27_0  
ipython                   5.4.1                    py27_2  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.1.0                    py27_0  
jinja2                    2.10             py27h70b8dc5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0                    py27_4  
jupyter_client            5.2.2                    py27_0  
jupyter_console           5.2.0            py27h9702a86_1  
jupyter_core              4.4.0            py27h5ea6ba4_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.15               hd9e47c5_0  
markupsafe                1.0              py27hd3c86fa_1  
mistune                   0.8.3                    py27_0  
nbconvert                 5.3.1            py27h6455e4c_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.0                  hd04f020_2  
notebook                  5.3.1                    py27_1  
numpy                     1.14.1                    <pip>
openssl                   1.0.2n               hdbc3d79_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py27hed78c4e_1  
pathlib2                  2.3.0            py27he09da1e_0  
pcre                      8.41                 hfb6ab37_1  
pexpect                   4.3.1                    py27_0  
pickleshare               0.7.4            py27h37e3d41_0  
pip                       9.0.1            py27h1567d89_4  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
ptyprocess                0.5.2            py27h70f6364_0  
pycosat                   0.6.3            py27h6c51c7e_0  
pycparser                 2.18             py27h0d28d88_1  
pygments                  2.2.0            py27h1a556bb_0  
pyopenssl                 17.5.0           py27hfda213f_0  
pyqt                      5.6.0            py27hf21fe59_6  
pysocks                   1.6.7            py27h1cff6a6_1  
python                    2.7.14              hde5916a_29  
python-dateutil           2.6.1            py27hd56c96b_1  
python.app                2                py27hf2d5e94_7  
pyzmq                     16.0.3           py27h91ccc67_0  
qt                        5.6.2               h9975529_14  
qtconsole                 4.3.1            py27hdc90b4f_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py27h9b2b37c_1  
ruamel_yaml               0.11.14          py27h31666c4_2  
scandir                   1.6              py27h97aa1ee_0  
scikit-learn              0.19.1                    <pip>
scipy                     1.0.0                     <pip>
send2trash                1.4.2                    py27_0  
setuptools                36.5.0           py27h2a45cec_0  
simplegeneric             0.8.1            py27h6db5e31_0  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.18.1           py27h6300f65_2  
six                       1.11.0           py27h7252ba3_1  
sklearn                   0.0                       <pip>
sqlite                    3.20.1               h7e4c145_2  
ssl_match_hostname        3.5.0.1          py27h8780752_2  
terminado                 0.8.1                    py27_0  
testpath                  0.3.1            py27h72d81a5_0  
tk                        8.6.7                h35a86e2_3  
tornado                   4.5.3                    py27_0  
traitlets                 4.3.2            py27hcf08151_0  
urllib3                   1.22             py27hc3787e9_0  
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1            py27h19a9f58_1  
wheel                     0.30.0           py27h677a027_1  
widgetsnbextension        3.1.0                    py27_0  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.2                ha360ad0_2  
zlib                      1.2.11               hf3cbc9b_2  

Wen-Fus-MacBook-Pro:bin wen-fulee$ ./conda info

     active environment : None
       user config file : /Users/wen-fulee/.condarc
 populated config files : 
          conda version : 4.4.10
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/pkgs
                          /Users/wen-fulee/.conda/pkgs
       envs directories : /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/envs
                          /Users/wen-fulee/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
